//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_registro_unico_aduanero.modelo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class computador
    {
        public int GUIDComputador { get; set; }
        public string Tipo { get; set; }
        public string Marca { get; set; }
        public string Sistema_Operativo { get; set; }
        public string Estado { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Cantidad_perifericos { get; set; }
    }
}
